### ISSUE TITLE
Refactor datasource configuration for wormhole

### ISSUE THREAD

**Issue by soulasuna** [zergclan/wormhole#221]
## Refactor datasource configuration for wormhole

> 1.  **For English only**, other languages will not accept.
> 2. Please pay attention on issues you submitted, because we maybe need more details.
> 3. If no response anymore and we cannot make decision by current information, we will **close it**.

### Describe the feature you would like.
1. Current configuration
```yaml
dataSources:
  ds-source:
    type: MySQL
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    catalog: ds_source
  ds-target:
    type: MySQL
    host: 127.0.0.1
    port: 3307
    username: root
    password: 123456
    catalog: ds_target
```

2. Refactored configuration
```yaml
dataSources:
  ds-source:
    type: MySQL
    url: jdbc:mysql://127.0.0.1:3306/ds_source?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    pool:
      minPoolSize: 1
      maxPoolSize: 50
      connectionTimeoutMilliseconds: 30000
      idleTimeoutMilliseconds: 60000
      maxLifetimeMilliseconds: 1800000
  ds-target:
    type: MySQL
    url: jdbc:mysql://127.0.0.1:3306/ds_target?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    pool:
      minPoolSize: 1
      maxPoolSize: 50
      connectionTimeoutMilliseconds: 30000
      idleTimeoutMilliseconds: 60000
      maxLifetimeMilliseconds: 1800000
```
